### ISSUE TITLE
cannot import name 'LevelDBException' from 'leveldb' (Possibly a packaging issue)

### ISSUE THREAD

**Issue by Kimiblock** [Amulet-Team/Amulet-Core#279]
**Describe the bug**
I'm making Arch packages for Amulet (Current one is too old and can't build properly) and Amulet Core. But as soon as I launch Amulet using `python -m amulet_map_editor`, it errors out.

Could you please tell me which dependency I'm missing? Thanks!

Logs:

```
↪ python -m amulet_map_editor
INFO - PyMCTranslate Version 257
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/usr/lib/python3.11/site-packages/amulet_map_editor/__init__.py", line 27, in <module>
    from amulet_map_editor.api.framework.app import open_level, close_level
  File "/usr/lib/python3.11/site-packages/amulet_map_editor/api/framework/__init__.py", line 1, in <module>
    from .app import AmuletApp
  File "/usr/lib/python3.11/site-packages/amulet_map_editor/api/framework/app.py", line 2, in <module>
    from . import amulet_ui
  File "/usr/lib/python3.11/site-packages/amulet_map_editor/api/framework/amulet_ui.py", line 8, in <module>
    from amulet.api.errors import LoaderNoneMatched
  File "/usr/lib/python3.11/site-packages/amulet/__init__.py", line 24, in <module>
    from amulet.level.load import load_level, load_format
  File "/usr/lib/python3.11/site-packages/amulet/level/__init__.py", line 1, in <module>
    from .load import load_format, load_level
  File "/usr/lib/python3.11/site-packages/amulet/level/load.py", line 9, in <module>
    from . import loader
  File "/usr/lib/python3.11/site-packages/amulet/level/loader.py", line 87, in <module>
    Formats = Loader(
              ^^^^^^^
  File "/usr/lib/python3.11/site-packages/amulet/level/loader.py", line 29, in __init__
    self._recursive_find(package_name)
  File "/usr/lib/python3.11/site-packages/amulet/level/loader.py", line 47, in _recursive_find
    self._recursive_find(sub_module_name)
  File "/usr/lib/python3.11/site-packages/amulet/level/loader.py", line 32, in _recursive_find
    module = importlib.import_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/amulet/level/formats/leveldb_world/__init__.py", line 1, in <module>
    from .format import LevelDBFormat
  File "/usr/lib/python3.11/site-packages/amulet/level/formats/leveldb_world/format.py", line 32, in <module>
    from leveldb import LevelDB, LevelDBException, LevelDBEncrypted
ImportError: cannot import name 'LevelDBException' from 'leveldb' (/usr/lib/python3.11/site-packages/leveldb.cpython-311-x86_64-linux-gnu.so)
```

**To Reproduce**
1. Build `python-amulet-core` and `amulet-map-editor`
2. Launch Amulet using `python -m amulet_map_editor`
3. See error

**Expected behavior**
Amulet launches without problem

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Program Version 1.9.20

**Additional context**
PKGBUILD @ https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-amulet-core

Installed leveldb packages:

```
local/leveldb 1.23-3
    A fast and lightweight key/value database library
local/python-leveldb 0.201-3
    Python bindings for leveldb database library
```

**Comment by gentlegiantJGC** [comment]
Have you installed [the leveldb library](https://github.com/Amulet-Team/Amulet-LevelDB)?

**Comment by Kimiblock** [comment]
Thanks for your advice!

I’ll try to package this dependency and see if it’s solved.

**Comment by Kimiblock** [comment]
This issue is solved after packaging [python-amulet-leveldb-git](https://aur.archlinux.org/packages/python-amulet-leveldb-git).
